GET http://localhost:3000/hello
Content-Type "application/json"

### 

GET http://localhost:3000/about
Content-Type: "application/json"

###

GET http://localhost:3000/products
Content-Type: "application/json

###